<?php

declare(strict_types=1);

namespace AA\PerformanceAnalyzer\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('symfony_performance_analyzer');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->info('Enable performance analysis')
            ->end()
            ->arrayNode('thresholds')
            ->addDefaultsIfNotSet()
            ->children()
            ->integerNode('max_memory_mb')
            ->defaultValue(256)
            ->info('Maximum memory usage in MB')
            ->end()
            ->integerNode('max_response_time_ms')
            ->defaultValue(500)
            ->info('Maximum response time in milliseconds')
            ->end()
            ->integerNode('max_db_queries')
            ->defaultValue(50)
            ->info('Maximum number of database queries')
            ->end()
            ->integerNode('max_cognitive_complexity')
            ->defaultValue(10)
            ->info('Maximum cognitive complexity score')
            ->end()
            ->end()
            ->end()
            ->arrayNode('analyzers')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('memory')
            ->defaultTrue()
            ->info('Enable memory usage analysis')
            ->end()
            ->booleanNode('n_plus_one')
            ->defaultTrue()
            ->info('Enable N+1 query detection')
            ->end()
            ->booleanNode('cognitive_complexity')
            ->defaultTrue()
            ->info('Enable cognitive complexity analysis')
            ->end()
            ->end()
            ->end()
            ->arrayNode('storage')
            ->addDefaultsIfNotSet()
            ->children()
            ->enumNode('type')
            ->values(['database', 'file'])
            ->defaultValue('database')
            ->end()
            ->scalarNode('file_path')
            ->defaultValue('%kernel.cache_dir%/performance')
            ->end()
            ->arrayNode('retention')
            ->addDefaultsIfNotSet()
            ->children()
            ->integerNode('days')
            ->defaultValue(30)
            ->min(1)
            ->info('Number of days to retain performance data')
            ->end()
            ->integerNode('max_records')
            ->defaultValue(10000)
            ->min(100)
            ->info('Maximum number of records to keep')
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->arrayNode('sampling')
            ->addDefaultsIfNotSet()
            ->children()
            ->floatNode('rate')
            ->defaultValue(1.0)
            ->min(0.0)
            ->max(1.0)
            ->info('Percentage of requests to analyze (0.0 to 1.0)')
            ->end()
            ->booleanNode('degraded_mode')
            ->defaultFalse()
            ->info('Enable degraded mode under heavy load')
            ->end()
            ->integerNode('degraded_threshold_ms')
            ->defaultValue(1000)
            ->info('Response time threshold for degraded mode (ms)')
            ->end()
            ->end()
            ->end()
            ->arrayNode('circuit_breaker')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->defaultFalse()
            ->info('Enable circuit breaker for external services')
            ->end()
            ->integerNode('failure_threshold')
            ->defaultValue(5)
            ->min(1)
            ->info('Number of failures before opening circuit')
            ->end()
            ->integerNode('retry_timeout')
            ->defaultValue(60)
            ->min(10)
            ->info('Seconds to wait before retrying')
            ->end()
            ->end()
            ->end()
            ->arrayNode('dashboard')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->end()
            ->scalarNode('route_prefix')
            ->defaultValue('/_performance')
            ->end()
            ->arrayNode('security')
            ->children()
            ->booleanNode('enable_firewall')
            ->defaultFalse()
            ->end()
            ->arrayNode('allowed_ips')
            ->scalarPrototype()->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->arrayNode('profiler')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->defaultTrue()
            ->end()
            ->booleanNode('toolbar')
            ->defaultTrue()
            ->end()
            ->end()
            ->end()
            ->arrayNode('ci_cd')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->defaultFalse()
            ->end()
            ->enumNode('level')
            ->values(['error', 'warning', 'notice'])
            ->defaultValue('warning')
            ->end()
            ->scalarNode('output_format')
            ->defaultValue('json')
            ->end()
            ->end()
            ->end()
            ->end();

        return $treeBuilder;
    }
}
