services:
    _defaults:
        autowire: true
        autoconfigure: true

    AA\PerformanceAnalyzer\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests}'

    AA\PerformanceAnalyzer\Analyzer\PerformanceAnalyzer:
        arguments:
            $analyzers: !tagged_iterator aa_performance_analyzer.analyzer

    AA\PerformanceAnalyzer\Analyzer\CodeAnalyzer:
        tags: ['aa_performance_analyzer.analyzer']

    assets.performance_analyzer:
        class: Symfony\Component\Asset\Package
        arguments:
            - '@assets.context'
        tags:
            - { name: assets.package, package_name: performanceanalyzer }